#ifndef ADC_INTERFACE_H_
#define ADC_INTERFACE_H_

void ADC_voidInit (void);

#define SINGLE_ENDED_INPUT_ADC0                                 0
#define SINGLE_ENDED_INPUT_ADC1                                 1
#define SINGLE_ENDED_INPUT_ADC2                                 2
#define SINGLE_ENDED_INPUT_ADC3                                 3
#define SINGLE_ENDED_INPUT_ADC4                                 4
#define SINGLE_ENDED_INPUT_ADC5                                 5
#define SINGLE_ENDED_INPUT_ADC6                                 6
#define SINGLE_ENDED_INPUT_ADC7                                 7
#define DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_10X      8
#define DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_10X      9
#define DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_200X     10
#define DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_200X     11
#define DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_10X      12
#define DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_10X      13
#define DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_200X     14
#define DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_200X     15
#define DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC1_1X       16
#define DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC1_1X       17
#define DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC1_1X       18
#define DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC1_1X       19
#define DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC1_1X       20
#define DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC1_1X       21
#define DIFFERENTIAL_INPUT_POSITIVE_ADC6_NEGATIVE_ADC1_1X       22
#define DIFFERENTIAL_INPUT_POSITIVE_ADC7_NEGATIVE_ADC1_1X       23
#define DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC2_1X       24
#define DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC2_1X       25
#define DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_1X       26
#define DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_1X       27
#define DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC2_1X       28
#define DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC2_1X       29
#define SINGLE_ENDED_INPUT_1.22V                                30
#define SINGLE_ENDED_INPUT_0V                                   31


/*
 *param ->  Copy_u8Channel
 *CHANNEL options:
 *SINGLE_ENDED_INPUT_ADC0
 *SINGLE_ENDED_INPUT_ADC1
 *SINGLE_ENDED_INPUT_ADC2
 *SINGLE_ENDED_INPUT_ADC3
 *SINGLE_ENDED_INPUT_ADC4
 *SINGLE_ENDED_INPUT_ADC5
 *SINGLE_ENDED_INPUT_ADC6
 *SINGLE_ENDED_INPUT_ADC7
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC6_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC7_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC2_1X
 *SINGLE_ENDED_INPUT_1.22V
 *SINGLE_ENDED_INPUT_0V
 *
 *Copy_u8Gain options :
 *                      1
 *                      10
 *                      200
 * */
u8 ADC_u8StartConversionSynch (u8 Copy_u8Channel,u8 Copy_u8Gain ,u16* Copy_pu16DigitalRead,u32 *Copy_pu32mVolt);
u8 ADC_u8StartConversionASynch (u8 Copy_u8Channel,u8 Copy_u8Gain ,u16* Copy_pu16DigitalRead,u32 *Copy_pu32mVolt,void (*Copy_pvNotification)(void));
#endif
