#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

/*Reference voltage options:
 * AREF
 * AVCC
 * INTERNAL_2.56V
 * */
#define ADC_REFERENCE_VOLTAGE  AVCC

/* Enter volt for AREF if you use it-> maximum 5v*/
#define AREF                   4
#define AVCC                   5
#define INTERNAL_2.56V         INTERNAL_2.56V

/*NEEDED resolution options:
 * 8
 * 10
 * */
#define ADC_RESOLUTION         10


/*PRESCALER options:
 *DIV_BY_2
 *DIV_BY_4
 *DIV_BY_8
 *DIV_BY_16
 *DIV_BY_32
 *DIV_BY_64
 *DIV_BY_128
 * */
#define ADC_PRESCALER              DIV_BY_2


/*CHANNEL options:
 *SINGLE_ENDED_INPUT_ADC0
 *SINGLE_ENDED_INPUT_ADC1
 *SINGLE_ENDED_INPUT_ADC2
 *SINGLE_ENDED_INPUT_ADC3
 *SINGLE_ENDED_INPUT_ADC4
 *SINGLE_ENDED_INPUT_ADC5
 *SINGLE_ENDED_INPUT_ADC6
 *SINGLE_ENDED_INPUT_ADC7
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC6_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC7_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC2_1X
 *SINGLE_ENDED_INPUT_1.22V
 *SINGLE_ENDED_INPUT_0V
 * */
//#define ADC_CHANNEL         SINGLE_ENDED_INPUT_ADC0


/*OPTIONS
 * SINGLE_CONVERSION_MODE
 * AUTO_TRIGGER
 * */
#define ADC_CONVERSION_MODE     AUTO_TRIGGER
/*IF YOU CHOOSE AUTO_TRIGGER mode , choose the mode of auto trigger
 * OPTIONS :
 *FREE_RUNNING_MODE
 *ANALOG_COMPARATOR
 *EXTERNAL_INTRRUPT_REQUEST_0
 *TIMER_COUNTER0_COMPARE_MATCH
 *TIMER_COUNTER0_OVERFLOW
 *TIMER_COUNTER_COMPARE_MATCH_B
 *TIMER_COUNTER1_OVERFLOW
 *TIMER_COUNTER1_CAPTURE_EVENT
 * */
#define AUTO_TRIGGER  FREE_RUNNING_MODE


#define ADC_u32TIMEOUT        500000

#endif
