#ifndef ADC_INTERFACE_H_
#define ADC_INTERFACE_H_

void ADC_voidInit (void);

/*
 *param ->  Copy_u8Channel
 *CHANNEL options:
 *SINGLE_ENDED_INPUT_ADC0
 *SINGLE_ENDED_INPUT_ADC1
 *SINGLE_ENDED_INPUT_ADC2
 *SINGLE_ENDED_INPUT_ADC3
 *SINGLE_ENDED_INPUT_ADC4
 *SINGLE_ENDED_INPUT_ADC5
 *SINGLE_ENDED_INPUT_ADC6
 *SINGLE_ENDED_INPUT_ADC7
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC0_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC0_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_10X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_200X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC6_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC7_NEGATIVE_ADC1_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC0_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC1_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC2_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC3_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC4_NEGATIVE_ADC2_1X
 *DIFFERENTIAL_INPUT_POSITIVE_ADC5_NEGATIVE_ADC2_1X
 *SINGLE_ENDED_INPUT_1.22V
 *SINGLE_ENDED_INPUT_0V
 *
 *Copy_u8Gain options :
 *                      1
 *                      10
 *                      200
 * */
u8 ADC_u8StartConversionSynch (u8 Copy_u8Channel,u8 Copy_u8Gain ,u16* Copy_pu16DigitalRead,u32 *Copy_pu32mVolt);
u8 ADC_u8StartConversionASynch (u8 Copy_u8Channel,u8 Copy_u8Gain ,u16* Copy_pu16DigitalRead,u32 *Copy_pu32mVolt,void (*Copy_pvNotification)(void));
#endif
